problema2: main.c print_read/print_read_dinamyc.c LU/factorization_lu.c gauss_pivoteo_total/solve_gauss_pt.c
	gcc -o problema2 main.c print_read/print_read_dinamyc.c LU/factorization_lu.c gauss_pivoteo_total/solve_gauss_pt.c matrix_math/matrix_math.c

run:
	./problema2
	
clean:
	rm ./problema2