problema 3: main.c diagonal/solve_diagonal.c gauss_seidel/gauss_seidel.c print_read/print_read.c
	gcc -o problema3 main.c \
	diagonal/solve_diagonal.c \
	gauss_seidel/gauss_seidel.c \
	print_read/print_read.c \
	gauss_pivoteo_total/solve_gauss_pt.c \
	jacobi/jacobi.c

run:
	./problema3

clean:
	rm problema3