tarjet = tarea12
objs = main.c \
matrix_math/matrix_math.c \
print_read/print_read.c QR/QR.c \
spline_cubic/spline_cubic.c
${tarjet}: ${objs}
	gcc -o ${tarjet} ${objs}

run:
	./${tarjet}

clean:
	rm ${tarjet}

